# 网站主题
theme: minima

# 网站基本信息
title: "微小企业人员管理系统"
description: |
  本系统旨在提升微小企业人员管理效率，涵盖应聘人员搜索与内部人员管理
  两大核心模块，助力企业优化人员配置，增强竞争力。

# 作者信息
author: "mxlz"

# 网站 URL 配置
url: "https://eoihbr.github.io/mxlz1/"    # 网站的基本 URL
baseurl: ""                       # 如果网站部署在子目录，设置为子目录名

# 语言和本地化设置
locale: "zh-CN"  # 设置中文区域

# 站点图标
favicon: "/assets/images/favicon.ico"  # 设置网站图标

# 网站的社交媒体链接
social:
  github: "https://github.com/eoihbr"  # GitHub 个人主页链接

# SEO 配置
seo:
  keywords: ["微小企业", "人员管理", "招聘", "人才搜索", "人员配置"]
  google_analytics: "UA-XXXXXXX-X"  # 如果有使用 Google Analytics，请填写 ID

# 站点主题自定义设置
# 可以在这里设置其他主题特性，例如颜色、字体等
theme_settings:
  primary_color: "#3498db"   # 设置主色调为蓝色
  font_family: "Arial, sans-serif"   # 设置字体为 Arial
  header_font_size: "24px"   # 设置头部字体大小

# 设置分页
paginate: 5   # 每页显示 5 篇文章

# 配置导航栏
nav:
  - title: "首页"
    url: "/"
  - title: "项目"
    url: "/projects"
  - title: "博客"
    url: "/blog"
  - title: "关于"
    url: "/about"

# 配置文章设置
posts:
  # 文章的默认布局
  default_layout: "post"

# 配置 Markdown 格式
markdown: kramdown   # 使用 kramdown 作为 Markdown 解析引擎

# 配置 Permalink（永久链接）
permalink: /:year/:month/:day/:title/   # 设置文章的 URL 格式

# 其他设置
exclude:
  - "README.md"  # 排除 README 文件不参与生成
  - "LICENSE"    # 排除 LICENSE 文件
